version: '2'
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
        - '3000:3000'
    expose:
      - '3000'
    links:
      - backend
    working_dir: /usr/local/frontend
    volumes:
      - ./frontend:/usr/local/frontend
    command: sh -c "npm run dev"

  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - '8080:8080'
    expose:
      - '8080'
    links:
      - mysql
    working_dir: /usr/local/backend/src
    environment:
      - GO111MODULE=on
      - PORT=8080
      - RUN_WITH_DEVAPPSERVER=1
    volumes:
      - ./backend:/usr/local/backend
    command: sh -c "rerun -watch ./ -ignore src/static -run go run main.go" # "go run main.go"

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: development
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: service
    ports:
      - '3306:3306'
    expose:
      - '3306'
